### ISSUE TITLE
Move JSDoc to dev dependency

### ISSUE THREAD

**Issue by FlorianK13** [open-pv/simshady#1]
jsdoc is a dependency of the package, but it should probably be a devDependency, right?

**Comment by khdlr** [comment]
Right, sounds like an oversight on my end.

**Comment by khdlr** [comment]
Addressed by 3c0f7c60d4f2f2ae6d9aa1117d9424ca9b475452 – jsdoc is actually not needed at all, because we have typedoc in the dev dependencies (jsdoc is probably a relic from back when we were playing around with some package templates?)
