### ISSUE TITLE
Bug hunting

### ISSUE THREAD

**Issue by MartGro** [open-pv/simshady#13]
Bug: 

![image](https://github.com/open-pv/simshady/assets/14249622/2e4bef96-58fd-40ac-87c5-7764501a5cee)
Some triangles show strange artifacts. 

What we tried: 
1) Check normals: The normals that are calculated seem to be fine, since coloring by normal works well 
![image](https://github.com/open-pv/simshady/assets/14249622/3c5413d4-43a3-472a-ab6f-5b0530c5c409)

2) check subdivision: When coloring points randomly, it seems that it is nicely subdivided

3) replacing the dot product in the ray tracing with 1 gives consistent results

**Comment by FlorianK13** [comment]
Solved with the referenced commit
