### ISSUE TITLE
Why only Bavaria?

### ISSUE THREAD

**Issue by spacekookie** [open-pv/simshady#19]
You say in your docs that you want to support places outside Bavaria. It would be good to outline and document what data and data source access is needed to accomplish this. 
Saying "it only works in bavaria" with no information how to potentially make it work in other places is a bit frustrating.

**Comment by FlorianK13** [comment]
We are currently working on that. The main issue is that every state in Germany has its own dataset and we need to connect them one by one. 
A list of data sets that can be used is here: https://github.com/OloOcki/awesome-citygml

**Comment by FlorianK13** [comment]
However we will have whole Germany (except two states) online within the next weeks.

**Comment by MartGro** [comment]
@spacekookie Now the website is online for all of Germany (https://www.openpv.de)
