### ISSUE TITLE
Delete hardcoded url for TIF files

### ISSUE THREAD

**Issue by khdlr** [open-pv/simshady#22]
Currently, our Code assumes that `average_direct_radiation.tif` is in lat-lon grid (EPSG:4326):
https://github.com/open-pv/simshady/blob/64739f3f93731214fac0d53f2522e2319bf091c1/src/sun.ts#L204-L209

However the actual data seems to be encoded in a different coordinate reference system (the geotiff metadata is missing the reference to which one though). This causes the "Purple Neuschwanstein"-Bug:

![image](https://github.com/user-attachments/assets/638866a3-03e9-418a-a5a8-8b998970b830)

What's happening here is that due to the wrong projection, a point outside of Germany is queried from the `average_direct_radiation.tif`, and these outside regions are filled with -999 as the nodata value.

**Comment by khdlr** [comment]
Suggested Fixes:

* [ ] Reproject the `average_direct_radiation.tif` to EPSG:4326

Either:
* [ ] Fill nodata values with a more meaningful value (e.g. nearest neighbor interpolation)
Or:
* [ ] Hard-code a fallback value in case the retrieved direct_radiation value is `NaN`

@FlorianK13 do you remember our source for the irradiance geotiff?

**Comment by FlorianK13** [comment]
Yes. The data comes from the dwd open data portal: [direct](https://opendata.dwd.de/climate_environment/CDC/grids_germany/annual/radiation_direct/) and [diffuse](https://opendata.dwd.de/climate_environment/CDC/grids_germany/annual/radiation_diffuse/)

There I downloaded all zipped folders 206-2023 and created one average. Sadly I cannot find the code anymore.

**Comment by khdlr** [comment]
Awesome, the documentation mentions the used projection: EPSG:31467 (3-degree Gauss-Kruger zone 3), which I can proudly announce I've never heard of :smile:

Still that's enough information to reproject to regular lat/lon values :+1:

**Comment by FlorianK13** [comment]
Moreover the openpv.de dependency should not be hardcoded in simshady - shame on me 😢

**Comment by khdlr** [comment]
Looking a lot better already:

![Screenshot from 2024-08-20 13-15-10](https://github.com/user-attachments/assets/25f61eb6-b46c-41b8-8244-c7faf0c8ccd9)

**Comment by khdlr** [comment]
While we're at it, we should probably add attribution to DWD for this data, right?

**Comment by FlorianK13** [comment]
> While we're at it, we should probably add attribution to DWD for this data, right?

But at openpv.de and not here, right?
